# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: true
apt_packages:
  - unixodbc-dev

script:
  - |
    R CMD build .
    travis_wait 60 R CMD check surf*tar.gz

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
