#' @title Real Datasets
#'
#' @description Amazonas state subset of the Brazilian Continous Household Survey,
#' containing data from paired observations in the 1st and 2nd quarters of 2018.
#'
#' @aliases dfr0 dfr1 real
#'
#' @docType data
#'
#' @usage data("real")
#'
#' @format Two objects of class \code{data.frame}: \code{dfr0, dfr0}
#'
#' @seealso \code{\link{dfa0}} for artificial data from a pseudo-population.
#'
#' @keywords real
"dfr0"

#' @title Artificial datasets
#'
#' @description Artificial paired datasets, obtained using a SRSWOR from a pseudo-population of 100 000 individuals.
#' @docType data
#'
#' @aliases df0 df1 artificial
#'
#' @usage data("artificial")
#'
#' @details The population was generated by this Markov chain:
#'
#' \tabular{lllll}{
#'        \tab      \tab           \tab t1       \tab          \cr
#'        \tab      \tab  1        \tab 2        \tab 3        \cr
#'        \tab 1    \tab  .720     \tab .135     \tab .045     \cr
#' t0     \tab 2    \tab  .015     \tab .030     \tab .005     \cr
#'        \tab 3    \tab  .005     \tab .005     \tab .040     \cr
#' }
#'
#' The \code{dfa0} contains the inclusion probabilities in the \code{prob} column.
#'
#' @format Two objects of class \code{data.frame}: \code{dfa0, dfa1}.
#'
#' @seealso \code{\link{dfr0}} for real data from a Brazilian survey.
#'
#' @keywords artificial
"df0"
